# permissions for end users to edit bitcoinnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitcoinnode-editor-role
rules:
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes/status
  verbs:
  - get
