# permissions for end users to view bitcoinnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitcoinnode-viewer-role
rules:
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes/status
  verbs:
  - get
