# permissions for end users to edit chainkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chainkey-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kiln-operator
    app.kubernetes.io/part-of: kiln-operator
    app.kubernetes.io/managed-by: kustomize
  name: chainkey-editor-role
rules:
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - chainkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - chainkeys/status
  verbs:
  - get
