# permissions for end users to view lightningnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightningnode-viewer-role
rules:
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes/status
  verbs:
  - get
