# permissions for end users to edit lightningnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightningnode-editor-role
rules:
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes/status
  verbs:
  - get
