
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes/finalizers
  verbs:
  - update
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - bitcoinnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes/finalizers
  verbs:
  - update
- apiGroups:
  - bitcoin.kiln-fired.github.io
  resources:
  - lightningnodes/status
  verbs:
  - get
  - patch
  - update
