apiVersion: bitcoin.kiln-fired.github.io/v1alpha1
kind: BitcoinNode
metadata:
  name: btcd
spec:
  mining:
    cpuMiningEnabled: false
    rewardAddress:
      secretName: chainkey-secret
    minBlocks: 400
    secondsPerBlock: 10
  rpcServer:
    certSecret: btcd-rpc-tls
    user: node-user
    password: st4cks4ts
