name: pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: check out code
        uses: actions/checkout@v2

      - name: build code
        shell: bash
        run:  make build

      - name: build container image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./${{ env.PROJECT_DIR }}/Dockerfile
          push: false
          tags: |
            quay.io/kiln-fired/kiln-operator:${{ github.sha }}
            quay.io/kiln-fired/kiln-operator:latest
            quay.io/kiln-fired/kiln-operator:${{ github.ref_name }}
