name: push

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: check out code
        uses: actions/checkout@v2

      - name: build code
        shell: bash
        run:  make

      - name: authenticate to container image registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: build container image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./${{ env.PROJECT_DIR }}/Dockerfile
          push: true
          tags: |
            quay.io/kiln-fired/kiln-operator:latest
