name: push

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: check out code
        uses: actions/checkout@v2

      - name: prepare build environment
        run: |
          # Create Binary Directory
          mkdir -p bin
          curl -L -o bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v1.27.0/operator-sdk_linux_amd64
          make controller-gen
          make kustomize
          echo bin >> $GITHUB_PATH
          chmod +x bin/*

      - name: build code
        shell: bash
        run:  make build

      - name: run controller tests
        shell: bash
        run:  make test

      - name: authenticate to container image registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: publish operator image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ env.PROJECT_DIR }}/Dockerfile
          push: true
          tags: |
            quay.io/kiln-fired/kiln-operator:latest

      - name: build bundle
        shell: bash
        run: make bundle IMG=quay.io/kiln-fired/kiln-operator:latest VERSION=0.0.1 DEFAULT_CHANNEL=alpha

      - name: publish bundle image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ env.PROJECT_DIR }}/bundle.Dockerfile
          push: true
          tags: |
            quay.io/kiln-fired/kiln-operator-bundle:latest

